Repository dahun-lee-daji/sidedish, pull requests merged in 2021-04, with the labels that each got.

#10 Feature/6/init UI
  SideDishApp/SideDishApp.xcodeproj/project.pbxproj
  SideDishApp/SideDishApp.xcodeproj/xcuserdata/idahun.xcuserdatad/xcschemes/xcschememanagement.plist
  SideDishApp/SideDishApp/Presentation/UI/View/Base.lproj/Main.storyboard
  SideDishApp/SideDishApp/Presentation/UI/View/DishCardCell.swift
  SideDishApp/SideDishApp/Presentation/UI/ViewController/ViewController.swift
Labels: feat, iOS

#12 iOS/feature/9/network
  README.md
  SideDishApp/SideDishApp.xcodeproj/project.pbxproj
  SideDishApp/SideDishApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  SideDishApp/SideDishApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  SideDishApp/SideDishApp.xcodeproj/project.xcworkspace/xcuserdata/ohking.xcuserdatad/UserInterfaceState.xcuserstate
  SideDishApp/SideDishApp.xcodeproj/xcuserdata/idahun.xcuserdatad/xcschemes/xcschememanagement.plist
  SideDishApp/SideDishApp.xcodeproj/xcuserdata/ohking.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  SideDishApp/SideDishApp.xcodeproj/xcuserdata/ohking.xcuserdatad/xcschemes/xcschememanagement.plist
  SideDishApp/SideDishApp/Application/AppDelegate.swift
  SideDishApp/SideDishApp/Application/SceneDelegate.swift
  SideDishApp/SideDishApp/Data/Network/DishNetworkManager.swift
  SideDishApp/SideDishApp/Data/Network/Endpoint.swift
  SideDishApp/SideDishApp/Data/Network/NetworkManager.swift
  SideDishApp/SideDishApp/Domain/Entity/Dish.swift
  SideDishApp/SideDishApp/Domain/UseCase/MenuListUseCase.swift
  SideDishApp/SideDishApp/Info.plist
  SideDishApp/SideDishApp/Presentation/UI/View/Base.lproj/Main.storyboard
  SideDishApp/SideDishApp/Presentation/UI/View/DishCardCell.swift
  SideDishApp/SideDishApp/Presentation/UI/ViewController/ViewController.swift
  SideDishApp/SideDishApp/Presentation/ViewModel/MenuListViewModel.swift
  SideDishApp/SideDishApp/SupportingFiles/Assets.xcassets/AccentColor.colorset/Contents.json
  SideDishApp/SideDishApp/SupportingFiles/Assets.xcassets/AppIcon.appiconset/Contents.json
  SideDishApp/SideDishApp/SupportingFiles/Assets.xcassets/Contents.json
  SideDishApp/SideDishApp/SupportingFiles/Base.lproj/LaunchScreen.storyboard
  SideDishApp/SideDishApp/SupportingFiles/Info.plist
Labels: feat, iOS

#16 iOS/Refactor/15/CellRegistration
  SideDishApp/SideDishApp.xcodeproj/project.pbxproj
  SideDishApp/SideDishApp/Presentation/UI/View/DishCell.swift
  SideDishApp/SideDishApp/Presentation/UI/View/DishCell.xib
  SideDishApp/SideDishApp/Presentation/UI/ViewController/DiffableProvider.swift
Labels: iOS, refactor

#22 iOS/feature/17/persistence
  SideDishApp/Pods/Pods.xcodeproj/xcuserdata/ohking.xcuserdatad/xcschemes/xcschememanagement.plist
  SideDishApp/SideDishApp.xcodeproj/project.pbxproj
  SideDishApp/SideDishApp.xcodeproj/project.xcworkspace/xcuserdata/ohking.xcuserdatad/UserInterfaceState.xcuserstate
  SideDishApp/SideDishApp.xcodeproj/xcuserdata/ohking.xcuserdatad/xcschemes/xcschememanagement.plist
  SideDishApp/SideDishApp.xcworkspace/xcuserdata/ohking.xcuserdatad/UserInterfaceState.xcuserstate
  SideDishApp/SideDishApp.xcworkspace/xcuserdata/ohking.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  SideDishApp/SideDishApp/Application/AppDelegate.swift
  SideDishApp/SideDishApp/Data/Network/DishNetworkManager.swift
  SideDishApp/SideDishApp/Data/Network/NetworkManager.swift
  SideDishApp/SideDishApp/Data/Persistence/CoreData.xcdatamodeld/CoreData.xcdatamodel/contents
  SideDishApp/SideDishApp/Data/Persistence/CoreDataMenuResponseStorage.swift
  SideDishApp/SideDishApp/Data/Persistence/DishesEntity+CoreDataClass.swift
  SideDishApp/SideDishApp/Data/Persistence/DishesEntity+CoreDataProperties.swift
  SideDishApp/SideDishApp/Data/Repository/MenuRepository.swift
  SideDishApp/SideDishApp/Domain/Entity/Dish.swift
  SideDishApp/SideDishApp/Domain/UseCase/MenuListUseCase.swift
  SideDishApp/SideDishApp/Presentation/UI/ViewController/DiffableProvider.swift
  SideDishApp/SideDishApp/Presentation/ViewModel/MenuListViewModel.swift
Labels: feat, iOS

#25 iOS/feature/24/loading view controller
  SideDishApp/Pods/Pods.xcodeproj/xcuserdata/ohking.xcuserdatad/xcschemes/xcschememanagement.plist
  SideDishApp/SideDishApp.xcodeproj/project.pbxproj
  SideDishApp/SideDishApp.xcodeproj/xcuserdata/ohking.xcuserdatad/xcschemes/xcschememanagement.plist
  SideDishApp/SideDishApp.xcworkspace/xcuserdata/ohking.xcuserdatad/UserInterfaceState.xcuserstate
  SideDishApp/SideDishApp.xcworkspace/xcuserdata/ohking.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  SideDishApp/SideDishApp/Presentation/UI/View/Base.lproj/Main.storyboard
  SideDishApp/SideDishApp/Presentation/UI/View/LoadingView.swift
  SideDishApp/SideDishApp/Presentation/UI/View/LoadingView.xib
  SideDishApp/SideDishApp/Presentation/UI/ViewController/LoadingViewController.swift
  SideDishApp/SideDishApp/Presentation/UI/ViewController/ViewController.swift
  SideDishApp/SideDishApp/Presentation/ViewModel/MenuListViewModel.swift
Labels: feat, iOS

#26 iOS/test/23/mock network
  SideDishApp/SideDishApp.xcodeproj/project.pbxproj
  SideDishApp/SideDishApp/Data/Network/MockNetworkManager.swift
  SideDishApp/SideDishApp/Data/Network/NetworkManager.swift
  SideDishApp/SideDishApp/Domain/Entity/Dish.swift
  SideDishApp/SideDishAppTests/Info.plist
  SideDishApp/SideDishAppTests/NetworkTests.swift
  SideDishApp/SideDishAppTests/SideDishAppTests.swift
  SideDishApp/SideDishAppTests/testData.json
Labels: iOS, test

#33 iOS/feature/32/detail view
  SideDishApp/SideDishApp.xcodeproj/project.pbxproj
  SideDishApp/SideDishApp.xcworkspace/xcuserdata/ohking.xcuserdatad/UserInterfaceState.xcuserstate
  SideDishApp/SideDishApp/Presentation/UI/View/Base.lproj/Main.storyboard
  SideDishApp/SideDishApp/Presentation/UI/ViewController/LoadingViewController.swift
  SideDishApp/SideDishApp/Presentation/UI/ViewController/MenuDetailController.swift
  SideDishApp/SideDishApp/Presentation/UI/ViewController/ViewController.swift
Labels: feat, iOS
